Repository CroudTech/Croud-Style-Guide, pull requests merged in 2018-05, with the labels that each got.

#79 Feature/arrow icons
  _templates/vue/component/prompt.js
  _templates/vue/functionalComponent/component.ejs.t
  _templates/vue/functionalComponent/prompt.js
  src/components/shared/buttons/DropdownIndicatorButton.vue
  src/components/shared/buttons/croud-dropdown-indicator-button.md
  src/components/shared/icons/ArrowIcon.vue
  src/components/shared/icons/croud-arrow-icon.md
  src/components/shared/layout/Panel.vue
  src/components/shared/layout/toggleHeader.vue
  styleguide.config.js
  test/unit/buttons/DropdownIndicatorButton.spec.js
  test/unit/buttons/__snapshots__/DropdownIndicatorButton.spec.js.snap
  test/unit/icons/ArrowIcon.spec.js
  test/unit/icons/__snapshots__/ArrowIcon.spec.js.snap
  test/unit/layout/Panel.spec.js
  test/unit/layout/__snapshots__/Panel.spec.js.snap
  test/unit/layout/__snapshots__/toggleHeader.spec.js.snap
  test/unit/layout/toggleHeader.spec.js
Labels: bug, enhancement, new component

#80 Feature/cc 1242 dropdown header component
  _templates/vue/component/prompt.js
  _templates/vue/functionalComponent/component.ejs.t
  _templates/vue/functionalComponent/prompt.js
  src/components/shared/buttons/DropdownIndicatorButton.vue
  src/components/shared/buttons/croud-dropdown-indicator-button.md
  src/components/shared/icons/ArrowIcon.vue
  src/components/shared/icons/croud-arrow-icon.md
  src/components/shared/layout/Panel.vue
  src/components/shared/layout/ToggleHeader.vue
  src/components/shared/layout/croud-toggle-header.md
  src/mixins/styleguidist.js
  styleguide.config.js
  test/unit/buttons/DropdownIndicatorButton.spec.js
  test/unit/buttons/__snapshots__/DropdownIndicatorButton.spec.js.snap
  test/unit/icons/ArrowIcon.spec.js
  test/unit/icons/__snapshots__/ArrowIcon.spec.js.snap
  test/unit/layout/Panel.spec.js
  test/unit/layout/ToggleHeader.spec.js
  test/unit/layout/__snapshots__/Panel.spec.js.snap
  test/unit/layout/__snapshots__/ToggleHeader.spec.js.snap
Labels: enhancement

#76 Save molecules
  src/components/shared/buttons/DropdownButton.vue
  src/components/shared/buttons/SaveButton.vue
  src/components/shared/buttons/SaveButtonWithDropdown.vue
  src/components/shared/buttons/croud-dropdown-button.md
  src/components/shared/buttons/croud-save-button-with-dropdown.md
  src/components/shared/buttons/croud-save-button.md
  test/unit/buttons/DropdownButton.spec.js
  test/unit/buttons/SaveButton.spec.js
  test/unit/buttons/SaveButtonWithDropdown.spec.js
  test/unit/buttons/__snapshots__/DropdownButton.spec.js.snap
  test/unit/buttons/__snapshots__/SaveButton.spec.js.snap
  test/unit/buttons/__snapshots__/SaveButtonWithDropdown.spec.js.snap
Labels: enhancement, new component
