Repository CroudTech/Croud-Style-Guide, pull requests merged in 2018-03, with the labels that each got.

#44 Progress bar css
  semantic/dist/semantic.css
  semantic/dist/semantic.min.css
  semantic/src/definitions/modules/progress.less
  semantic/src/site/modules/progress.variables
Labels: enhancement

#53 Multi selector refactor
  src/components/shared/misc/SummarisedMultiSelector.vue
Labels: bug, enhancement

#52 Sheduler editor defaults
  src/components/shared/mixins/schedule.js
  src/components/shared/scheduler/SchedulerEditor.vue
  styleguide.config.js
  test/unit/schedule/SchedulerEditor.spec.js
  test/unit/schedule/SchedulerModal.spec.js
  test/unit/schedule/SchedulerText.spec.js
  test/unit/schedule/__snapshots__/SchedulerEditor.spec.js.snap
  test/unit/schedule/__snapshots__/SchedulerModal.spec.js.snap
Labels: bug, enhancement, help wanted

#51 WIP: Scheduler refactor
  src/components/shared/forms/DatePicker.vue
  src/components/shared/mixins/schedule.js
  src/components/shared/scheduler/SchedulerEditor.vue
  src/components/shared/scheduler/SchedulerModal.vue
  src/components/shared/scheduler/croud-scheduler-editor.md
  src/components/shared/scheduler/croud-scheduler-modal.md
  styleguide.config.js
  test/unit/schedule/SchedulerEditor.spec.js
  test/unit/schedule/SchedulerModal.spec.js
  test/unit/schedule/SchedulerText.spec.js
  test/unit/schedule/__snapshots__/SchedulerEditor.spec.js.snap
  test/unit/schedule/__snapshots__/SchedulerModal.spec.js.snap
Labels: enhancement, help wanted

#56 Multi selector tests
  test/unit/misc/SummarisedMultiSelector.spec.js
  test/unit/misc/__snapshots__/SummarisedMultiSelector.spec.js.snap
Labels: enhancement

#47 Feature/scheduler
  package.json
  semantic/dist/semantic.css
  semantic/dist/semantic.min.css
  semantic/src/site/elements/button.overrides
  src/components/shared/forms/DatePicker.vue
  src/components/shared/mixins/schedule.js
  src/components/shared/scheduler/SchedulerEditor.vue
  src/components/shared/scheduler/SchedulerModal.vue
  src/components/shared/scheduler/SchedulerText.vue
  src/components/shared/scheduler/croud-scheduler-editor.md
  src/components/shared/scheduler/croud-scheduler-modal.md
  src/components/shared/scheduler/croud-scheduler-text.md
  src/mixins/styleguidist.js
  styleguide.config.js
  test/unit/schedule/SchedulerEditor.spec.js
  test/unit/schedule/SchedulerModal.spec.js
  test/unit/schedule/SchedulerText.spec.js
  test/unit/schedule/__snapshots__/SchedulerEditor.spec.js.snap
  test/unit/schedule/__snapshots__/SchedulerModal.spec.js.snap
  test/unit/schedule/__snapshots__/SchedulerText.spec.js.snap
  yarn.lock
Labels: enhancement

#46 Feature/summarised multi selector
  src/components/shared/misc/SummarisedMultiSelector.vue
  src/components/shared/misc/croud-summarised-mutli-selector.md
  src/mixins/styleguidist.js
  test/unit/misc/SummarisedMultiSelector.spec.js
  test/unit/misc/__snapshots__/SummarisedMultiSelector.spec.js.snap
Labels: enhancement
